### ISSUE TITLE
Attaching a router to a subnet with a non-gateway IP

### ISSUE THREAD

**Issue by oneswig** [stackhpc/ansible-role-os-networks#18]
It appears that this syntax from https://docs.ansible.com/ansible/latest/modules/os_router_module.html doesn't work and claims the subnet is not found:

```
    interfaces:
      - net: private-net
        subnet: private-subnet
        portip: 10.1.1.10
```
